# Generated by Django 6.0.6 on 2026-06-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_secondname', models.CharField(blank=True, max_length=50, null=True)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_second_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('user_genre', models.CharField(max_length=50)),
                ('user_dateofbirth', models.DateField()),
                ('user_cedula', models.CharField(max_length=20, unique=True)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_address', models.CharField(max_length=255)),
                ('user_isactive', models.BooleanField(default=True)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
        ),
    ]
