# Generated by Django 6.0.6 on 2026-06-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('reservation_firstname', models.CharField(max_length=100)),
                ('reservation_secondname', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_lastname', models.CharField(max_length=100)),
                ('reservation_second_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_dateofbirth', models.DateField()),
                ('reservation_cedula', models.CharField(max_length=30)),
                ('reservation_email', models.EmailField(max_length=254)),
                ('reservation_phone', models.CharField(max_length=20)),
                ('reservation_address', models.CharField(max_length=255)),
                ('reservation_genre', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('license_country', models.CharField(max_length=50)),
                ('reservation_status', models.CharField(max_length=30)),
                ('reservation_created', models.DateTimeField(auto_now_add=True)),
                ('reservation_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
