# Generated by Django 6.0.6 on 2026-06-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('status_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_license_plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('vehicle_seats', models.PositiveIntegerField()),
                ('vehicle_doors', models.PositiveIntegerField()),
                ('vehicle_engine_type', models.CharField(max_length=100)),
                ('vehicle_transmission', models.CharField(max_length=100)),
                ('vehicle_mileage', models.PositiveIntegerField()),
                ('vehicle_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vehicle_hour_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehicle_location', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField(blank=True)),
                ('vehicle_image', models.JSONField()),
                ('vehicle_created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclecategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclestatus')),
            ],
        ),
    ]
